name: Coleta diária de notícias

on:
  schedule:
    - cron: '40 20 * * *'  # Executar às 23:40 UTC-3
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar script de coleta
      run: python teste.py

    - name: Fazer commit dos resultados
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add noticias/
        git commit -m "Atualização automática: notícias do dia"
        git push
