name: Coleta diária de notícias

on:
  schedule:
    - cron: '30 20 * * *'  # Executar às 23:30 UTC-3
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar script de coleta
      run: python teste.py

    - name: Commit CSV
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Notícias $(date +'%d/%m/%Y')"
        git push
