name: Coleta diária de notícias

on:
  schedule:
    - cron: '30 2 * * *'  # Executar às 23:30 UTC-3
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar script de coleta
      run: python teste.py

    - name: Commit CSV
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git"
        git add noticias/
        git commit -m "Notícias $(date +'%d/%m/%Y')"
        git push origin HEAD:main
